---
title: Spectra database summary
author: Alexey Shiklomanov
output: html_document
---

```{r setup, echo=FALSE}
suppressPackageStartupMessages({
    library(specprocess)
    library(knitr)
    library(ggplot2)
    library(ggmap)
})
specdb <- src_sqlite('leaf_spectra.db')
opts_chunk$set(echo = FALSE, message = FALSE)
```

# Summary

## By project

```{r projectspectra}
spectra_counts <- tbl(specdb, 'samples') %>%
    inner_join(tbl(specdb, 'spectra_info')) %>%
    count(projectcode, spectratype, sort = TRUE) %>%
    collect()
kable(spectra_counts, caption = 'Number of spectra by project and spectra type')
```

```{r projectsize, echo = FALSE}
project_counts <- tbl(specdb, 'samples') %>%
    count(projectcode, sort = TRUE) %>%
    collect()
kable(project_counts, caption = 'Number of samples per project')
```

```{r spectratraitbyproject, echo = FALSE}
spectrait <- tbl(specdb, 'samples') %>%
    inner_join(tbl(specdb, 'spectra_info')) %>%
    semi_join(tbl(specdb, 'trait_data')) %>%
    count(projectcode, sort = TRUE) %>%
    collect
kable(spectrait, caption = 'Pairwise spectra-trait observations by project')
```

## By trait

```{r spectatraitbytrait, echo = FALSE}
bytrait <- tbl(specdb, 'samples') %>%
    inner_join(tbl(specdb, 'spectra_info')) %>%
    inner_join(tbl(specdb, 'trait_data')) %>%
    count(trait, sort = TRUE) %>%
    collect()
kable(bytrait, caption = 'Pairwise spectra-trait observations by trait')
```

## By location

```{r samplemap, echo = FALSE, fig.cap='Geographic distribution of samples'}
samples_by_site <- tbl(specdb, 'samples') %>%
    left_join(tbl(specdb, 'plots')) %>%
    left_join(tbl(specdb, 'sites')) %>%
    collect() %>%
    group_by(sitecode, projectcode) %>%
    summarize(mean_lat = mean(latitude, na.rm = TRUE), 
              mean_lon = mean(longitude, na.rm = TRUE),
              nsamp = n())
x_lims <- round(range(samples_by_site$mean_lon, na.rm = TRUE))
y_lims <- round(range(samples_by_site$mean_lat, na.rm = TRUE))

ggplot(samples_by_site) +
    aes(x = mean_lon, y = mean_lat, size = nsamp, color = projectcode) +
    borders('world', xlim = x_lims, ylim = y_lims) +
    geom_point()
```

## By species

```{r species, echo = FALSE, fig.cap = 'Samples by species'}
samples_by_species <- tbl(specdb, 'samples') %>%
    count(speciescode, sort = TRUE) %>%
    left_join(tbl(specdb, 'species')) %>%
    collect() %>%
    mutate(speciescode = factor(speciescode, levels = speciescode))
kable(samples_by_species %>% select(scientificname, n) %>% head(20),
      caption = 'Top 20 species')
ggplot(samples_by_species) + 
    aes(x = speciescode, y = n) +
    geom_bar(stat = 'identity') +
    theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())
```

```{r growthform, echo = FALSE, fig.cap = 'Samples by species: growth form'}
samples_attr <- tbl(specdb, 'samples') %>%
    left_join(tbl(specdb, 'species_attributes')) %>%
    collect()
ggplot(samples_attr) + 
    aes(x = growth_form) + 
    geom_bar()
```

```{r pstype, echo = FALSE, fig.cap = 'Samples by species: photosynthetic pathway'}
ggplot(samples_attr) + 
    aes(x = ps_type) + 
    geom_bar()
```

```{r myco_asso, echo = FALSE, fig.cap = 'Samples by species: mycorrhizal association'}
ggplot(samples_attr) + 
    aes(x = myco_asso) + 
    geom_bar()
```

```{r shade_tolerance, echo = FALSE, fig.cap = 'Samples by species: shade tolerance'}
ggplot(samples_attr) + 
    aes(x = shade_tolerance) + 
    geom_bar()
```

# Issues

## Missing latitude/longitude

```{r missingplot, echo = FALSE}
missing_plots <- tbl(specdb, 'plots') %>%
    filter(is.na(latitude) | is.na(longitude)) %>%
    inner_join(tbl(specdb, 'samples')) %>%
    count(sitecode, sort = TRUE) %>%
    collect()
kable(missing_plots, caption = 'Sites with missing coordinates') 
```

## Missing species

```{r missingspecies, echo = FALSE}
missing_species <- tbl(specdb, 'samples') %>%
    filter(is.na(speciescode)) %>%
    count(projectcode, sort = TRUE) %>%
    collect()
kable(missing_species, caption = 'Samples with unidentified species, by project')
```

## Samples with no spectra
```{r nospecsamples, echo = FALSE}
missing_spectra <- tbl(specdb, 'samples') %>%
    anti_join(tbl(specdb, 'spectra_info')) %>%
    count(projectcode, sort = TRUE) %>%
    collect
kable(missing_spectra, caption = 'Samples with no associated spectra, by project')
```
